name: CI

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run linters, execute script and publish result.json to GitHub Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas==2.3.*" openpyxl ruff

      - name: Run ruff (show results in CI log)
        run: ruff .

      - name: Run analysis script and capture output
        run: |
          python execute.py > result.json

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: result.json
